### ISSUE TITLE
Implement pre-build hooks

### ISSUE THREAD

**Issue by dominikbraun** [verless/verless#158]
The `build` section in `verless.yml` should allow the user to define pre-build hooks:

```yaml
build:
    before:
        - sass styles/default.scss themes/default/css/style.css
```
