### ISSUE TITLE
Add theme configuration

### ISSUE THREAD

**Issue by dominikbraun** [verless/verless#161]
verless should provide the option to add a theme configuration in a `theme.yml` file inside the particular theme directory. A possible structure of this configuration would be something like this:

```yaml
name: dark-theme # The theme name that users specify inside verless.yml
build:
    before:
        - sass style.scss generated/style.css
```
