### ISSUE TITLE
`redirect` plugin

### ISSUE THREAD

**Issue by dominikbraun** [verless/verless#279]
There should be a `redirect` plugin to redirect from one content page to another:

```yaml
# content/my-old-page.md
---
Title: My old Page
Redirect: /my-new-page
---
```

Just like the other plugins, the `redirect` plugin would have to be explicitly enabled in `verless.yml `.
