### ISSUE TITLE
Introduce content types

### ISSUE THREAD

**Issue by dominikbraun** [verless/verless#90]
This will supersede #58.

Content types should be configurable in the `verless.yml` file with an own `types` key:

```yaml
types:
    blog-post:
        template: post.html
```

The only content type property at this time is `template`. The may infer the template file in case it isn't configured explicitly at a later time, but for this first implementation, the `template` key should be mandatory.

Just like in the original issue #58, the YAML key in the Markdown Front Matter should be `Type`.
